<script>
import ace from "ace-builds";

import modeAbapUrl from 'ace-builds/src-noconflict/mode-abap?url';
ace.config.setModuleUrl('ace/mode/abap', modeAbapUrl);
import modeAbcUrl from 'ace-builds/src-noconflict/mode-abc?url';
ace.config.setModuleUrl('ace/mode/abc', modeAbcUrl);
import modeActionscriptUrl from 'ace-builds/src-noconflict/mode-actionscript?url';
ace.config.setModuleUrl('ace/mode/actionscript', modeActionscriptUrl);
import modeAdaUrl from 'ace-builds/src-noconflict/mode-ada?url';
ace.config.setModuleUrl('ace/mode/ada', modeAdaUrl);
import modeAldaUrl from 'ace-builds/src-noconflict/mode-alda?url';
ace.config.setModuleUrl('ace/mode/alda', modeAldaUrl);
import modeApache_confUrl from 'ace-builds/src-noconflict/mode-apache_conf?url';
ace.config.setModuleUrl('ace/mode/apache_conf', modeApache_confUrl);
import modeApexUrl from 'ace-builds/src-noconflict/mode-apex?url';
ace.config.setModuleUrl('ace/mode/apex', modeApexUrl);
import modeApplescriptUrl from 'ace-builds/src-noconflict/mode-applescript?url';
ace.config.setModuleUrl('ace/mode/applescript', modeApplescriptUrl);
import modeAqlUrl from 'ace-builds/src-noconflict/mode-aql?url';
ace.config.setModuleUrl('ace/mode/aql', modeAqlUrl);
import modeAsciidocUrl from 'ace-builds/src-noconflict/mode-asciidoc?url';
ace.config.setModuleUrl('ace/mode/asciidoc', modeAsciidocUrl);
import modeAslUrl from 'ace-builds/src-noconflict/mode-asl?url';
ace.config.setModuleUrl('ace/mode/asl', modeAslUrl);
import modeAssembly_x86Url from 'ace-builds/src-noconflict/mode-assembly_x86?url';
ace.config.setModuleUrl('ace/mode/assembly_x86', modeAssembly_x86Url);
import modeAutohotkeyUrl from 'ace-builds/src-noconflict/mode-autohotkey?url';
ace.config.setModuleUrl('ace/mode/autohotkey', modeAutohotkeyUrl);
import modeBatchfileUrl from 'ace-builds/src-noconflict/mode-batchfile?url';
ace.config.setModuleUrl('ace/mode/batchfile', modeBatchfileUrl);
import modeC9searchUrl from 'ace-builds/src-noconflict/mode-c9search?url';
ace.config.setModuleUrl('ace/mode/c9search', modeC9searchUrl);
import modeCirruUrl from 'ace-builds/src-noconflict/mode-cirru?url';
ace.config.setModuleUrl('ace/mode/cirru', modeCirruUrl);
import modeClojureUrl from 'ace-builds/src-noconflict/mode-clojure?url';
ace.config.setModuleUrl('ace/mode/clojure', modeClojureUrl);
import modeCobolUrl from 'ace-builds/src-noconflict/mode-cobol?url';
ace.config.setModuleUrl('ace/mode/cobol', modeCobolUrl);
import modeCoffeeUrl from 'ace-builds/src-noconflict/mode-coffee?url';
ace.config.setModuleUrl('ace/mode/coffee', modeCoffeeUrl);
import modeColdfusionUrl from 'ace-builds/src-noconflict/mode-coldfusion?url';
ace.config.setModuleUrl('ace/mode/coldfusion', modeColdfusionUrl);
import modeCrystalUrl from 'ace-builds/src-noconflict/mode-crystal?url';
ace.config.setModuleUrl('ace/mode/crystal', modeCrystalUrl);
import modeCsharpUrl from 'ace-builds/src-noconflict/mode-csharp?url';
ace.config.setModuleUrl('ace/mode/csharp', modeCsharpUrl);
import modeCsound_documentUrl from 'ace-builds/src-noconflict/mode-csound_document?url';
ace.config.setModuleUrl('ace/mode/csound_document', modeCsound_documentUrl);
import modeCsound_orchestraUrl from 'ace-builds/src-noconflict/mode-csound_orchestra?url';
ace.config.setModuleUrl('ace/mode/csound_orchestra', modeCsound_orchestraUrl);
import modeCsound_scoreUrl from 'ace-builds/src-noconflict/mode-csound_score?url';
ace.config.setModuleUrl('ace/mode/csound_score', modeCsound_scoreUrl);
import modeCspUrl from 'ace-builds/src-noconflict/mode-csp?url';
ace.config.setModuleUrl('ace/mode/csp', modeCspUrl);
import modeCssUrl from 'ace-builds/src-noconflict/mode-css?url';
ace.config.setModuleUrl('ace/mode/css', modeCssUrl);
import modeCUrlyUrl from 'ace-builds/src-noconflict/mode-curly?url';
ace.config.setModuleUrl('ace/mode/curly', modeCUrlyUrl);
import modeC_cppUrl from 'ace-builds/src-noconflict/mode-c_cpp?url';
ace.config.setModuleUrl('ace/mode/c_cpp', modeC_cppUrl);
import modeDUrl from 'ace-builds/src-noconflict/mode-d?url';
ace.config.setModuleUrl('ace/mode/d', modeDUrl);
import modeDartUrl from 'ace-builds/src-noconflict/mode-dart?url';
ace.config.setModuleUrl('ace/mode/dart', modeDartUrl);
import modeDiffUrl from 'ace-builds/src-noconflict/mode-diff?url';
ace.config.setModuleUrl('ace/mode/diff', modeDiffUrl);
import modeDjangoUrl from 'ace-builds/src-noconflict/mode-django?url';
ace.config.setModuleUrl('ace/mode/django', modeDjangoUrl);
import modeDockerfileUrl from 'ace-builds/src-noconflict/mode-dockerfile?url';
ace.config.setModuleUrl('ace/mode/dockerfile', modeDockerfileUrl);
import modeDotUrl from 'ace-builds/src-noconflict/mode-dot?url';
ace.config.setModuleUrl('ace/mode/dot', modeDotUrl);
import modeDroolsUrl from 'ace-builds/src-noconflict/mode-drools?url';
ace.config.setModuleUrl('ace/mode/drools', modeDroolsUrl);
import modeEdifactUrl from 'ace-builds/src-noconflict/mode-edifact?url';
ace.config.setModuleUrl('ace/mode/edifact', modeEdifactUrl);
import modeEiffelUrl from 'ace-builds/src-noconflict/mode-eiffel?url';
ace.config.setModuleUrl('ace/mode/eiffel', modeEiffelUrl);
import modeEjsUrl from 'ace-builds/src-noconflict/mode-ejs?url';
ace.config.setModuleUrl('ace/mode/ejs', modeEjsUrl);
import modeElixirUrl from 'ace-builds/src-noconflict/mode-elixir?url';
ace.config.setModuleUrl('ace/mode/elixir', modeElixirUrl);
import modeElmUrl from 'ace-builds/src-noconflict/mode-elm?url';
ace.config.setModuleUrl('ace/mode/elm', modeElmUrl);
import modeErlangUrl from 'ace-builds/src-noconflict/mode-erlang?url';
ace.config.setModuleUrl('ace/mode/erlang', modeErlangUrl);
import modeForthUrl from 'ace-builds/src-noconflict/mode-forth?url';
ace.config.setModuleUrl('ace/mode/forth', modeForthUrl);
import modeFortranUrl from 'ace-builds/src-noconflict/mode-fortran?url';
ace.config.setModuleUrl('ace/mode/fortran', modeFortranUrl);
import modeFsharpUrl from 'ace-builds/src-noconflict/mode-fsharp?url';
ace.config.setModuleUrl('ace/mode/fsharp', modeFsharpUrl);
import modeFslUrl from 'ace-builds/src-noconflict/mode-fsl?url';
ace.config.setModuleUrl('ace/mode/fsl', modeFslUrl);
import modeFtlUrl from 'ace-builds/src-noconflict/mode-ftl?url';
ace.config.setModuleUrl('ace/mode/ftl', modeFtlUrl);
import modeGcodeUrl from 'ace-builds/src-noconflict/mode-gcode?url';
ace.config.setModuleUrl('ace/mode/gcode', modeGcodeUrl);
import modeGherkinUrl from 'ace-builds/src-noconflict/mode-gherkin?url';
ace.config.setModuleUrl('ace/mode/gherkin', modeGherkinUrl);
import modeGitignoreUrl from 'ace-builds/src-noconflict/mode-gitignore?url';
ace.config.setModuleUrl('ace/mode/gitignore', modeGitignoreUrl);
import modeGlslUrl from 'ace-builds/src-noconflict/mode-glsl?url';
ace.config.setModuleUrl('ace/mode/glsl', modeGlslUrl);
import modeGobstonesUrl from 'ace-builds/src-noconflict/mode-gobstones?url';
ace.config.setModuleUrl('ace/mode/gobstones', modeGobstonesUrl);
import modeGolangUrl from 'ace-builds/src-noconflict/mode-golang?url';
ace.config.setModuleUrl('ace/mode/golang', modeGolangUrl);
import modeGraphqlschemaUrl from 'ace-builds/src-noconflict/mode-graphqlschema?url';
ace.config.setModuleUrl('ace/mode/graphqlschema', modeGraphqlschemaUrl);
import modeGroovyUrl from 'ace-builds/src-noconflict/mode-groovy?url';
ace.config.setModuleUrl('ace/mode/groovy', modeGroovyUrl);
import modeHamlUrl from 'ace-builds/src-noconflict/mode-haml?url';
ace.config.setModuleUrl('ace/mode/haml', modeHamlUrl);
import modeHandlebarsUrl from 'ace-builds/src-noconflict/mode-handlebars?url';
ace.config.setModuleUrl('ace/mode/handlebars', modeHandlebarsUrl);
import modeHaskellUrl from 'ace-builds/src-noconflict/mode-haskell?url';
ace.config.setModuleUrl('ace/mode/haskell', modeHaskellUrl);
import modeHaskell_cabalUrl from 'ace-builds/src-noconflict/mode-haskell_cabal?url';
ace.config.setModuleUrl('ace/mode/haskell_cabal', modeHaskell_cabalUrl);
import modeHaxeUrl from 'ace-builds/src-noconflict/mode-haxe?url';
ace.config.setModuleUrl('ace/mode/haxe', modeHaxeUrl);
import modeHjsonUrl from 'ace-builds/src-noconflict/mode-hjson?url';
ace.config.setModuleUrl('ace/mode/hjson', modeHjsonUrl);
import modeHtmlUrl from 'ace-builds/src-noconflict/mode-html?url';
ace.config.setModuleUrl('ace/mode/html', modeHtmlUrl);
import modeHtml_elixirUrl from 'ace-builds/src-noconflict/mode-html_elixir?url';
ace.config.setModuleUrl('ace/mode/html_elixir', modeHtml_elixirUrl);
import modeHtml_rubyUrl from 'ace-builds/src-noconflict/mode-html_ruby?url';
ace.config.setModuleUrl('ace/mode/html_ruby', modeHtml_rubyUrl);
import modeIniUrl from 'ace-builds/src-noconflict/mode-ini?url';
ace.config.setModuleUrl('ace/mode/ini', modeIniUrl);
import modeIoUrl from 'ace-builds/src-noconflict/mode-io?url';
ace.config.setModuleUrl('ace/mode/io', modeIoUrl);
import modeIonUrl from 'ace-builds/src-noconflict/mode-ion?url';
ace.config.setModuleUrl('ace/mode/ion', modeIonUrl);
import modeJackUrl from 'ace-builds/src-noconflict/mode-jack?url';
ace.config.setModuleUrl('ace/mode/jack', modeJackUrl);
import modeJadeUrl from 'ace-builds/src-noconflict/mode-jade?url';
ace.config.setModuleUrl('ace/mode/jade', modeJadeUrl);
import modeJavaUrl from 'ace-builds/src-noconflict/mode-java?url';
ace.config.setModuleUrl('ace/mode/java', modeJavaUrl);
import modeJavascriptUrl from 'ace-builds/src-noconflict/mode-javascript?url';
ace.config.setModuleUrl('ace/mode/javascript', modeJavascriptUrl);
import modeJsonUrl from 'ace-builds/src-noconflict/mode-json?url';
ace.config.setModuleUrl('ace/mode/json', modeJsonUrl);
import modeJson5Url from 'ace-builds/src-noconflict/mode-json5?url';
ace.config.setModuleUrl('ace/mode/json5', modeJson5Url);
import modeJsoniqUrl from 'ace-builds/src-noconflict/mode-jsoniq?url';
ace.config.setModuleUrl('ace/mode/jsoniq', modeJsoniqUrl);
import modeJspUrl from 'ace-builds/src-noconflict/mode-jsp?url';
ace.config.setModuleUrl('ace/mode/jsp', modeJspUrl);
import modeJssmUrl from 'ace-builds/src-noconflict/mode-jssm?url';
ace.config.setModuleUrl('ace/mode/jssm', modeJssmUrl);
import modeJsxUrl from 'ace-builds/src-noconflict/mode-jsx?url';
ace.config.setModuleUrl('ace/mode/jsx', modeJsxUrl);
import modeJuliaUrl from 'ace-builds/src-noconflict/mode-julia?url';
ace.config.setModuleUrl('ace/mode/julia', modeJuliaUrl);
import modeKotlinUrl from 'ace-builds/src-noconflict/mode-kotlin?url';
ace.config.setModuleUrl('ace/mode/kotlin', modeKotlinUrl);
import modeLatexUrl from 'ace-builds/src-noconflict/mode-latex?url';
ace.config.setModuleUrl('ace/mode/latex', modeLatexUrl);
import modeLatteUrl from 'ace-builds/src-noconflict/mode-latte?url';
ace.config.setModuleUrl('ace/mode/latte', modeLatteUrl);
import modeLessUrl from 'ace-builds/src-noconflict/mode-less?url';
ace.config.setModuleUrl('ace/mode/less', modeLessUrl);
import modeLiquidUrl from 'ace-builds/src-noconflict/mode-liquid?url';
ace.config.setModuleUrl('ace/mode/liquid', modeLiquidUrl);
import modeLispUrl from 'ace-builds/src-noconflict/mode-lisp?url';
ace.config.setModuleUrl('ace/mode/lisp', modeLispUrl);
import modeLivescriptUrl from 'ace-builds/src-noconflict/mode-livescript?url';
ace.config.setModuleUrl('ace/mode/livescript', modeLivescriptUrl);
import modeLogiqlUrl from 'ace-builds/src-noconflict/mode-logiql?url';
ace.config.setModuleUrl('ace/mode/logiql', modeLogiqlUrl);
import modeLogtalkUrl from 'ace-builds/src-noconflict/mode-logtalk?url';
ace.config.setModuleUrl('ace/mode/logtalk', modeLogtalkUrl);
import modeLslUrl from 'ace-builds/src-noconflict/mode-lsl?url';
ace.config.setModuleUrl('ace/mode/lsl', modeLslUrl);
import modeLuaUrl from 'ace-builds/src-noconflict/mode-lua?url';
ace.config.setModuleUrl('ace/mode/lua', modeLuaUrl);
import modeLuapageUrl from 'ace-builds/src-noconflict/mode-luapage?url';
ace.config.setModuleUrl('ace/mode/luapage', modeLuapageUrl);
import modeLuceneUrl from 'ace-builds/src-noconflict/mode-lucene?url';
ace.config.setModuleUrl('ace/mode/lucene', modeLuceneUrl);
import modeMakefileUrl from 'ace-builds/src-noconflict/mode-makefile?url';
ace.config.setModuleUrl('ace/mode/makefile', modeMakefileUrl);
import modeMarkdownUrl from 'ace-builds/src-noconflict/mode-markdown?url';
ace.config.setModuleUrl('ace/mode/markdown', modeMarkdownUrl);
import modeMaskUrl from 'ace-builds/src-noconflict/mode-mask?url';
ace.config.setModuleUrl('ace/mode/mask', modeMaskUrl);
import modeMatlabUrl from 'ace-builds/src-noconflict/mode-matlab?url';
ace.config.setModuleUrl('ace/mode/matlab', modeMatlabUrl);
import modeMazeUrl from 'ace-builds/src-noconflict/mode-maze?url';
ace.config.setModuleUrl('ace/mode/maze', modeMazeUrl);
import modeMediawikiUrl from 'ace-builds/src-noconflict/mode-mediawiki?url';
ace.config.setModuleUrl('ace/mode/mediawiki', modeMediawikiUrl);
import modeMelUrl from 'ace-builds/src-noconflict/mode-mel?url';
ace.config.setModuleUrl('ace/mode/mel', modeMelUrl);
import modeMipsUrl from 'ace-builds/src-noconflict/mode-mips?url';
ace.config.setModuleUrl('ace/mode/mips', modeMipsUrl);
import modeMixalUrl from 'ace-builds/src-noconflict/mode-mixal?url';
ace.config.setModuleUrl('ace/mode/mixal', modeMixalUrl);
import modeMushcodeUrl from 'ace-builds/src-noconflict/mode-mushcode?url';
ace.config.setModuleUrl('ace/mode/mushcode', modeMushcodeUrl);
import modeMysqlUrl from 'ace-builds/src-noconflict/mode-mysql?url';
ace.config.setModuleUrl('ace/mode/mysql', modeMysqlUrl);
import modeNginxUrl from 'ace-builds/src-noconflict/mode-nginx?url';
ace.config.setModuleUrl('ace/mode/nginx', modeNginxUrl);
import modeNimUrl from 'ace-builds/src-noconflict/mode-nim?url';
ace.config.setModuleUrl('ace/mode/nim', modeNimUrl);
import modeNixUrl from 'ace-builds/src-noconflict/mode-nix?url';
ace.config.setModuleUrl('ace/mode/nix', modeNixUrl);
import modeNsisUrl from 'ace-builds/src-noconflict/mode-nsis?url';
ace.config.setModuleUrl('ace/mode/nsis', modeNsisUrl);
import modeNunjucksUrl from 'ace-builds/src-noconflict/mode-nunjucks?url';
ace.config.setModuleUrl('ace/mode/nunjucks', modeNunjucksUrl);
import modeObjectivecUrl from 'ace-builds/src-noconflict/mode-objectivec?url';
ace.config.setModuleUrl('ace/mode/objectivec', modeObjectivecUrl);
import modeOcamlUrl from 'ace-builds/src-noconflict/mode-ocaml?url';
ace.config.setModuleUrl('ace/mode/ocaml', modeOcamlUrl);
import modePartiqlUrl from 'ace-builds/src-noconflict/mode-partiql?url';
ace.config.setModuleUrl('ace/mode/partiql', modePartiqlUrl);
import modePascalUrl from 'ace-builds/src-noconflict/mode-pascal?url';
ace.config.setModuleUrl('ace/mode/pascal', modePascalUrl);
import modePerlUrl from 'ace-builds/src-noconflict/mode-perl?url';
ace.config.setModuleUrl('ace/mode/perl', modePerlUrl);
import modePgsqlUrl from 'ace-builds/src-noconflict/mode-pgsql?url';
ace.config.setModuleUrl('ace/mode/pgsql', modePgsqlUrl);
import modePhpUrl from 'ace-builds/src-noconflict/mode-php?url';
ace.config.setModuleUrl('ace/mode/php', modePhpUrl);
import modePhp_laravel_bladeUrl from 'ace-builds/src-noconflict/mode-php_laravel_blade?url';
ace.config.setModuleUrl('ace/mode/php_laravel_blade', modePhp_laravel_bladeUrl);
import modePigUrl from 'ace-builds/src-noconflict/mode-pig?url';
ace.config.setModuleUrl('ace/mode/pig', modePigUrl);
import modePlain_textUrl from 'ace-builds/src-noconflict/mode-plain_text?url';
ace.config.setModuleUrl('ace/mode/plain_text', modePlain_textUrl);
import modePowershellUrl from 'ace-builds/src-noconflict/mode-powershell?url';
ace.config.setModuleUrl('ace/mode/powershell', modePowershellUrl);
import modePraatUrl from 'ace-builds/src-noconflict/mode-praat?url';
ace.config.setModuleUrl('ace/mode/praat', modePraatUrl);
import modePrismaUrl from 'ace-builds/src-noconflict/mode-prisma?url';
ace.config.setModuleUrl('ace/mode/prisma', modePrismaUrl);
import modePrologUrl from 'ace-builds/src-noconflict/mode-prolog?url';
ace.config.setModuleUrl('ace/mode/prolog', modePrologUrl);
import modePropertiesUrl from 'ace-builds/src-noconflict/mode-properties?url';
ace.config.setModuleUrl('ace/mode/properties', modePropertiesUrl);
import modeProtobufUrl from 'ace-builds/src-noconflict/mode-protobuf?url';
ace.config.setModuleUrl('ace/mode/protobuf', modeProtobufUrl);
import modePuppetUrl from 'ace-builds/src-noconflict/mode-puppet?url';
ace.config.setModuleUrl('ace/mode/puppet', modePuppetUrl);
import modePythonUrl from 'ace-builds/src-noconflict/mode-python?url';
ace.config.setModuleUrl('ace/mode/python', modePythonUrl);
import modeQmlUrl from 'ace-builds/src-noconflict/mode-qml?url';
ace.config.setModuleUrl('ace/mode/qml', modeQmlUrl);
import modeRUrl from 'ace-builds/src-noconflict/mode-r?url';
ace.config.setModuleUrl('ace/mode/r', modeRUrl);
import modeRakuUrl from 'ace-builds/src-noconflict/mode-raku?url';
ace.config.setModuleUrl('ace/mode/raku', modeRakuUrl);
import modeRazorUrl from 'ace-builds/src-noconflict/mode-razor?url';
ace.config.setModuleUrl('ace/mode/razor', modeRazorUrl);
import modeRdocUrl from 'ace-builds/src-noconflict/mode-rdoc?url';
ace.config.setModuleUrl('ace/mode/rdoc', modeRdocUrl);
import modeRedUrl from 'ace-builds/src-noconflict/mode-red?url';
ace.config.setModuleUrl('ace/mode/red', modeRedUrl);
import modeRedshiftUrl from 'ace-builds/src-noconflict/mode-redshift?url';
ace.config.setModuleUrl('ace/mode/redshift', modeRedshiftUrl);
import modeRhtmlUrl from 'ace-builds/src-noconflict/mode-rhtml?url';
ace.config.setModuleUrl('ace/mode/rhtml', modeRhtmlUrl);
import modeRobotUrl from 'ace-builds/src-noconflict/mode-robot?url';
ace.config.setModuleUrl('ace/mode/robot', modeRobotUrl);
import modeRstUrl from 'ace-builds/src-noconflict/mode-rst?url';
ace.config.setModuleUrl('ace/mode/rst', modeRstUrl);
import modeRubyUrl from 'ace-builds/src-noconflict/mode-ruby?url';
ace.config.setModuleUrl('ace/mode/ruby', modeRubyUrl);
import modeRustUrl from 'ace-builds/src-noconflict/mode-rust?url';
ace.config.setModuleUrl('ace/mode/rust', modeRustUrl);
import modeSacUrl from 'ace-builds/src-noconflict/mode-sac?url';
ace.config.setModuleUrl('ace/mode/sac', modeSacUrl);
import modeSassUrl from 'ace-builds/src-noconflict/mode-sass?url';
ace.config.setModuleUrl('ace/mode/sass', modeSassUrl);
import modeScadUrl from 'ace-builds/src-noconflict/mode-scad?url';
ace.config.setModuleUrl('ace/mode/scad', modeScadUrl);
import modeScalaUrl from 'ace-builds/src-noconflict/mode-scala?url';
ace.config.setModuleUrl('ace/mode/scala', modeScalaUrl);
import modeSchemeUrl from 'ace-builds/src-noconflict/mode-scheme?url';
ace.config.setModuleUrl('ace/mode/scheme', modeSchemeUrl);
import modeScryptUrl from 'ace-builds/src-noconflict/mode-scrypt?url';
ace.config.setModuleUrl('ace/mode/scrypt', modeScryptUrl);
import modeScssUrl from 'ace-builds/src-noconflict/mode-scss?url';
ace.config.setModuleUrl('ace/mode/scss', modeScssUrl);
import modeShUrl from 'ace-builds/src-noconflict/mode-sh?url';
ace.config.setModuleUrl('ace/mode/sh', modeShUrl);
import modeSjsUrl from 'ace-builds/src-noconflict/mode-sjs?url';
ace.config.setModuleUrl('ace/mode/sjs', modeSjsUrl);
import modeSlimUrl from 'ace-builds/src-noconflict/mode-slim?url';
ace.config.setModuleUrl('ace/mode/slim', modeSlimUrl);
import modeSmartyUrl from 'ace-builds/src-noconflict/mode-smarty?url';
ace.config.setModuleUrl('ace/mode/smarty', modeSmartyUrl);
import modeSmithyUrl from 'ace-builds/src-noconflict/mode-smithy?url';
ace.config.setModuleUrl('ace/mode/smithy', modeSmithyUrl);
import modeSnippetsUrl from 'ace-builds/src-noconflict/mode-snippets?url';
ace.config.setModuleUrl('ace/mode/snippets', modeSnippetsUrl);
import modeSoy_templateUrl from 'ace-builds/src-noconflict/mode-soy_template?url';
ace.config.setModuleUrl('ace/mode/soy_template', modeSoy_templateUrl);
import modeSpaceUrl from 'ace-builds/src-noconflict/mode-space?url';
ace.config.setModuleUrl('ace/mode/space', modeSpaceUrl);
import modeSparqlUrl from 'ace-builds/src-noconflict/mode-sparql?url';
ace.config.setModuleUrl('ace/mode/sparql', modeSparqlUrl);
import modeSqlUrl from 'ace-builds/src-noconflict/mode-sql?url';
ace.config.setModuleUrl('ace/mode/sql', modeSqlUrl);
import modeSqlserverUrl from 'ace-builds/src-noconflict/mode-sqlserver?url';
ace.config.setModuleUrl('ace/mode/sqlserver', modeSqlserverUrl);
import modeStylusUrl from 'ace-builds/src-noconflict/mode-stylus?url';
ace.config.setModuleUrl('ace/mode/stylus', modeStylusUrl);
import modeSvgUrl from 'ace-builds/src-noconflict/mode-svg?url';
ace.config.setModuleUrl('ace/mode/svg', modeSvgUrl);
import modeSwiftUrl from 'ace-builds/src-noconflict/mode-swift?url';
ace.config.setModuleUrl('ace/mode/swift', modeSwiftUrl);
import modeTclUrl from 'ace-builds/src-noconflict/mode-tcl?url';
ace.config.setModuleUrl('ace/mode/tcl', modeTclUrl);
import modeTerraformUrl from 'ace-builds/src-noconflict/mode-terraform?url';
ace.config.setModuleUrl('ace/mode/terraform', modeTerraformUrl);
import modeTexUrl from 'ace-builds/src-noconflict/mode-tex?url';
ace.config.setModuleUrl('ace/mode/tex', modeTexUrl);
import modeTextUrl from 'ace-builds/src-noconflict/mode-text?url';
ace.config.setModuleUrl('ace/mode/text', modeTextUrl);
import modeTextileUrl from 'ace-builds/src-noconflict/mode-textile?url';
ace.config.setModuleUrl('ace/mode/textile', modeTextileUrl);
import modeTomlUrl from 'ace-builds/src-noconflict/mode-toml?url';
ace.config.setModuleUrl('ace/mode/toml', modeTomlUrl);
import modeTsxUrl from 'ace-builds/src-noconflict/mode-tsx?url';
ace.config.setModuleUrl('ace/mode/tsx', modeTsxUrl);
import modeTurtleUrl from 'ace-builds/src-noconflict/mode-turtle?url';
ace.config.setModuleUrl('ace/mode/turtle', modeTurtleUrl);
import modeTwigUrl from 'ace-builds/src-noconflict/mode-twig?url';
ace.config.setModuleUrl('ace/mode/twig', modeTwigUrl);
import modeTypescriptUrl from 'ace-builds/src-noconflict/mode-typescript?url';
ace.config.setModuleUrl('ace/mode/typescript', modeTypescriptUrl);
import modeValaUrl from 'ace-builds/src-noconflict/mode-vala?url';
ace.config.setModuleUrl('ace/mode/vala', modeValaUrl);
import modeVbscriptUrl from 'ace-builds/src-noconflict/mode-vbscript?url';
ace.config.setModuleUrl('ace/mode/vbscript', modeVbscriptUrl);
import modeVelocityUrl from 'ace-builds/src-noconflict/mode-velocity?url';
ace.config.setModuleUrl('ace/mode/velocity', modeVelocityUrl);
import modeVerilogUrl from 'ace-builds/src-noconflict/mode-verilog?url';
ace.config.setModuleUrl('ace/mode/verilog', modeVerilogUrl);
import modeVhdlUrl from 'ace-builds/src-noconflict/mode-vhdl?url';
ace.config.setModuleUrl('ace/mode/vhdl', modeVhdlUrl);
import modeVisualforceUrl from 'ace-builds/src-noconflict/mode-visualforce?url';
ace.config.setModuleUrl('ace/mode/visualforce', modeVisualforceUrl);
import modeWollokUrl from 'ace-builds/src-noconflict/mode-wollok?url';
ace.config.setModuleUrl('ace/mode/wollok', modeWollokUrl);
import modeXmlUrl from 'ace-builds/src-noconflict/mode-xml?url';
ace.config.setModuleUrl('ace/mode/xml', modeXmlUrl);
import modeXqueryUrl from 'ace-builds/src-noconflict/mode-xquery?url';
ace.config.setModuleUrl('ace/mode/xquery', modeXqueryUrl);
import modeYamlUrl from 'ace-builds/src-noconflict/mode-yaml?url';
ace.config.setModuleUrl('ace/mode/yaml', modeYamlUrl);
import modeZeekUrl from 'ace-builds/src-noconflict/mode-zeek?url';
ace.config.setModuleUrl('ace/mode/zeek', modeZeekUrl);



import workerBaseUrl from 'ace-builds/src-noconflict/worker-base?url';
ace.config.setModuleUrl('ace/mode/base_worker', workerBaseUrl);
import workerCoffeeUrl from 'ace-builds/src-noconflict/worker-coffee?url';
ace.config.setModuleUrl('ace/mode/coffee_worker', workerCoffeeUrl);
import workerCssUrl from 'ace-builds/src-noconflict/worker-css?url';
ace.config.setModuleUrl('ace/mode/css_worker', workerCssUrl);
import workerHtmlUrl from 'ace-builds/src-noconflict/worker-html?url';
ace.config.setModuleUrl('ace/mode/html_worker', workerHtmlUrl);
import workerJavascriptUrl from 'ace-builds/src-noconflict/worker-javascript?url';
ace.config.setModuleUrl('ace/mode/javascript_worker', workerJavascriptUrl);
import workerJsonUrl from 'ace-builds/src-noconflict/worker-json?url';
ace.config.setModuleUrl('ace/mode/json_worker', workerJsonUrl);
import workerLuaUrl from 'ace-builds/src-noconflict/worker-lua?url';
ace.config.setModuleUrl('ace/mode/lua_worker', workerLuaUrl);
import workerPhpUrl from 'ace-builds/src-noconflict/worker-php?url';
ace.config.setModuleUrl('ace/mode/php_worker', workerPhpUrl);
import workerXmlUrl from 'ace-builds/src-noconflict/worker-xml?url';
ace.config.setModuleUrl('ace/mode/xml_worker', workerXmlUrl);
import workerXqueryUrl from 'ace-builds/src-noconflict/worker-xquery?url';
ace.config.setModuleUrl('ace/mode/xquery_worker', workerXqueryUrl);
import workerYamlUrl from 'ace-builds/src-noconflict/worker-yaml?url';
ace.config.setModuleUrl('ace/mode/yaml_worker', workerYamlUrl);
</script>